---
npmName: gopadjs
npmVersion: 3.3.3
supportsES6: true
useSingleRequestParameter: true
withNodeImports: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: model
enablePostProcessFile: true

...
